name: Generate ABIs

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.sol'

jobs:
  gen-abi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Truffle globally
        run: npm install -g truffle sol-merger
  
      - name: Install abigen
        run: go install github.com/ethereum/go-ethereum/cmd/abigen@latest

      - name: Write secret.json file
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          MAINNET_ENDPOINT: ${{ secrets.MAINNET_ENDPOINT }}
          GOERLI_ENDPOINT: ${{ secrets.GOERLI_ENDPOINT }}
          BSCTEST_ENDPOINT: ${{ secrets.BSCTEST_ENDPOINT }}
          BSC_ENDPOINT: ${{ secrets.BSC_ENDPOINT }}
          ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}
          BSC_API: ${{ secrets.BSC_API }}
        run: |
          cat <<EOF > .secret.json
          {
            "mnemonic": "${MNEMONIC}",
            "mainnet_endpoint": "${MAINNET_ENDPOINT}",
            "goerli_endpoint": "${GOERLI_ENDPOINT}",
            "bsctest_endpoint": "${BSCTEST_ENDPOINT}",
            "bsc_endpoint": "${BSC_ENDPOINT}",
            "etherscan_api": "${ETHERSCAN_API}",
            "bsc_api": "${BSC_API}"
          }
          EOF
  
      - name: Generate ABI files for changed Solidity files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Pull Request Number: $PR_NUMBER"
          
          # Fetch the list of changed files in the PR
          FILES=$(gh pr view $PR_NUMBER --json files --jq '.files[].path' | grep '\.sol$')
          echo "Changed Solidity files: $FILES"

          npm install
          truffle compile
          
          for FILE in $FILES; do
            CONTRACT_NAME=$(basename "$FILE" .sol)
            jq -r ".bytecode" build/contracts/$CONTRACT_NAME.json > ./build/$CONTRACT_NAME.bin
            jq -r ".abi" build/contracts/$CONTRACT_NAME.json > ./build/$CONTRACT_NAME.abi
            abigen --abi=build/$CONTRACT_NAME.abi --bin build/$CONTRACT_NAME.bin --pkg=go-binding --type=$CONTRACT_NAME --out=go-binding/$CONTRACT_NAME.go
          done
      - name: Commit and push the generated ABI files
        run: |
          git config --global user.email "bot@bitmark.com"
          git config --global user.name "Bitmark Bot"
          git add go-binding/*.go
          git commit -m "Generate and commit ABI files for Pull Requests: $PR_NUMBER" || echo "No changes to commit"
          git push